# coding: utf-8

# flake8: noqa
"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.1.7
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from product_catalogue_py_rest_client.models.compilation_dto import CompilationDto
from product_catalogue_py_rest_client.models.compilation_l3_relation_dto import CompilationL3RelationDto
from product_catalogue_py_rest_client.models.product_l0_dist_dto import ProductL0DistDto
from product_catalogue_py_rest_client.models.product_l0_instrument_file_dto import ProductL0InstrumentFileDto
from product_catalogue_py_rest_client.models.product_l0_src_dto import ProductL0SrcDto
from product_catalogue_py_rest_client.models.product_l3_dist_dto import ProductL3DistDto
from product_catalogue_py_rest_client.models.product_l3_src_dto import ProductL3SrcDto
from product_catalogue_py_rest_client.models.relation_summary_dto import RelationSummaryDto
from product_catalogue_py_rest_client.models.survey_dto import SurveyDto
from product_catalogue_py_rest_client.models.survey_l0_relation_dto import SurveyL0RelationDto
from product_catalogue_py_rest_client.models.survey_l3_relation_dto import SurveyL3RelationDto
