# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.1.15
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from product_catalogue_py_rest_client.configuration import Configuration


class ProductL0InstrumentFile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'l0_instrument_file': 'str'
    }

    attribute_map = {
        'id': 'id',
        'l0_instrument_file': 'l0InstrumentFile'
    }

    def __init__(self, id=None, l0_instrument_file=None, local_vars_configuration=None):  # noqa: E501
        """ProductL0InstrumentFile - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._l0_instrument_file = None
        self.discriminator = None

        self.id = id
        self.l0_instrument_file = l0_instrument_file

    @property
    def id(self):
        """Gets the id of this ProductL0InstrumentFile.  # noqa: E501


        :return: The id of this ProductL0InstrumentFile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductL0InstrumentFile.


        :param id: The id of this ProductL0InstrumentFile.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def l0_instrument_file(self):
        """Gets the l0_instrument_file of this ProductL0InstrumentFile.  # noqa: E501


        :return: The l0_instrument_file of this ProductL0InstrumentFile.  # noqa: E501
        :rtype: str
        """
        return self._l0_instrument_file

    @l0_instrument_file.setter
    def l0_instrument_file(self, l0_instrument_file):
        """Sets the l0_instrument_file of this ProductL0InstrumentFile.


        :param l0_instrument_file: The l0_instrument_file of this ProductL0InstrumentFile.  # noqa: E501
        :type l0_instrument_file: str
        """
        if self.local_vars_configuration.client_side_validation and l0_instrument_file is None:  # noqa: E501
            raise ValueError("Invalid value for `l0_instrument_file`, must not be `None`")  # noqa: E501

        self._l0_instrument_file = l0_instrument_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductL0InstrumentFile):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductL0InstrumentFile):
            return True

        return self.to_dict() != other.to_dict()
