# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.1.12
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from product_catalogue_py_rest_client.configuration import Configuration


class ProductL0InstrumentFileDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'coverage_file': 'str',
        'instrument_file': 'str'
    }

    attribute_map = {
        'coverage_file': 'coverageFile',
        'instrument_file': 'instrumentFile'
    }

    def __init__(self, coverage_file=None, instrument_file=None, local_vars_configuration=None):  # noqa: E501
        """ProductL0InstrumentFileDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._coverage_file = None
        self._instrument_file = None
        self.discriminator = None

        self.coverage_file = coverage_file
        self.instrument_file = instrument_file

    @property
    def coverage_file(self):
        """Gets the coverage_file of this ProductL0InstrumentFileDto.  # noqa: E501

        Location of shapefile describing instrument file extent  # noqa: E501

        :return: The coverage_file of this ProductL0InstrumentFileDto.  # noqa: E501
        :rtype: str
        """
        return self._coverage_file

    @coverage_file.setter
    def coverage_file(self, coverage_file):
        """Sets the coverage_file of this ProductL0InstrumentFileDto.

        Location of shapefile describing instrument file extent  # noqa: E501

        :param coverage_file: The coverage_file of this ProductL0InstrumentFileDto.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and coverage_file is None:  # noqa: E501
            raise ValueError("Invalid value for `coverage_file`, must not be `None`")  # noqa: E501

        self._coverage_file = coverage_file

    @property
    def instrument_file(self):
        """Gets the instrument_file of this ProductL0InstrumentFileDto.  # noqa: E501

        Location of instrument file  # noqa: E501

        :return: The instrument_file of this ProductL0InstrumentFileDto.  # noqa: E501
        :rtype: str
        """
        return self._instrument_file

    @instrument_file.setter
    def instrument_file(self, instrument_file):
        """Sets the instrument_file of this ProductL0InstrumentFileDto.

        Location of instrument file  # noqa: E501

        :param instrument_file: The instrument_file of this ProductL0InstrumentFileDto.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and instrument_file is None:  # noqa: E501
            raise ValueError("Invalid value for `instrument_file`, must not be `None`")  # noqa: E501

        self._instrument_file = instrument_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductL0InstrumentFileDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductL0InstrumentFileDto):
            return True

        return self.to_dict() != other.to_dict()
