# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from product_catalogue_py_rest_client.configuration import Configuration


class ProductL3Src(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'default_style': 'Style',
        'available_styles': 'list[Style]',
        'uuid': 'str',
        'name': 'str',
        'srs': 'str',
        'vertical_datum': 'str',
        'metadata_persistent_id': 'str',
        'resolution': 'str',
        'product_tif_location': 'str',
        'product_bag_location': 'str',
        'sort_order': 'float'
    }

    attribute_map = {
        'id': 'id',
        'default_style': 'defaultStyle',
        'available_styles': 'availableStyles',
        'uuid': 'uuid',
        'name': 'name',
        'srs': 'srs',
        'vertical_datum': 'verticalDatum',
        'metadata_persistent_id': 'metadataPersistentId',
        'resolution': 'resolution',
        'product_tif_location': 'productTifLocation',
        'product_bag_location': 'productBagLocation',
        'sort_order': 'sortOrder'
    }

    def __init__(self, id=None, default_style=None, available_styles=None, uuid=None, name=None, srs=None, vertical_datum=None, metadata_persistent_id=None, resolution=None, product_tif_location=None, product_bag_location=None, sort_order=None, local_vars_configuration=None):  # noqa: E501
        """ProductL3Src - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._default_style = None
        self._available_styles = None
        self._uuid = None
        self._name = None
        self._srs = None
        self._vertical_datum = None
        self._metadata_persistent_id = None
        self._resolution = None
        self._product_tif_location = None
        self._product_bag_location = None
        self._sort_order = None
        self.discriminator = None

        self.id = id
        if default_style is not None:
            self.default_style = default_style
        if available_styles is not None:
            self.available_styles = available_styles
        self.uuid = uuid
        self.name = name
        self.srs = srs
        self.vertical_datum = vertical_datum
        self.metadata_persistent_id = metadata_persistent_id
        self.resolution = resolution
        self.product_tif_location = product_tif_location
        self.product_bag_location = product_bag_location
        self.sort_order = sort_order

    @property
    def id(self):
        """Gets the id of this ProductL3Src.  # noqa: E501


        :return: The id of this ProductL3Src.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductL3Src.


        :param id: The id of this ProductL3Src.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def default_style(self):
        """Gets the default_style of this ProductL3Src.  # noqa: E501


        :return: The default_style of this ProductL3Src.  # noqa: E501
        :rtype: Style
        """
        return self._default_style

    @default_style.setter
    def default_style(self, default_style):
        """Sets the default_style of this ProductL3Src.


        :param default_style: The default_style of this ProductL3Src.  # noqa: E501
        :type default_style: Style
        """

        self._default_style = default_style

    @property
    def available_styles(self):
        """Gets the available_styles of this ProductL3Src.  # noqa: E501


        :return: The available_styles of this ProductL3Src.  # noqa: E501
        :rtype: list[Style]
        """
        return self._available_styles

    @available_styles.setter
    def available_styles(self, available_styles):
        """Sets the available_styles of this ProductL3Src.


        :param available_styles: The available_styles of this ProductL3Src.  # noqa: E501
        :type available_styles: list[Style]
        """

        self._available_styles = available_styles

    @property
    def uuid(self):
        """Gets the uuid of this ProductL3Src.  # noqa: E501


        :return: The uuid of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ProductL3Src.


        :param uuid: The uuid of this ProductL3Src.  # noqa: E501
        :type uuid: str
        """
        if self.local_vars_configuration.client_side_validation and uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this ProductL3Src.  # noqa: E501


        :return: The name of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductL3Src.


        :param name: The name of this ProductL3Src.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def srs(self):
        """Gets the srs of this ProductL3Src.  # noqa: E501


        :return: The srs of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._srs

    @srs.setter
    def srs(self, srs):
        """Sets the srs of this ProductL3Src.


        :param srs: The srs of this ProductL3Src.  # noqa: E501
        :type srs: str
        """
        if self.local_vars_configuration.client_side_validation and srs is None:  # noqa: E501
            raise ValueError("Invalid value for `srs`, must not be `None`")  # noqa: E501

        self._srs = srs

    @property
    def vertical_datum(self):
        """Gets the vertical_datum of this ProductL3Src.  # noqa: E501


        :return: The vertical_datum of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._vertical_datum

    @vertical_datum.setter
    def vertical_datum(self, vertical_datum):
        """Sets the vertical_datum of this ProductL3Src.


        :param vertical_datum: The vertical_datum of this ProductL3Src.  # noqa: E501
        :type vertical_datum: str
        """
        if self.local_vars_configuration.client_side_validation and vertical_datum is None:  # noqa: E501
            raise ValueError("Invalid value for `vertical_datum`, must not be `None`")  # noqa: E501
        allowed_values = ["Unknown", "LAT", "AHD", "LMSL", "WGS84", "NAD83(HARN)", "NAD83(CORSxx)", "NAD83(NSRSxx)", "NAD83(PACPxx)", "NAD83(MARPxx)", "ITRFxx", "NAVD88", "NGVD29", "EGM2008", "EGM1996", "EGM1984", "MLLW", "MLW", "MHW", "MHHW", "DTL", "MTL", "LWD"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and vertical_datum not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `vertical_datum` ({0}), must be one of {1}"  # noqa: E501
                .format(vertical_datum, allowed_values)
            )

        self._vertical_datum = vertical_datum

    @property
    def metadata_persistent_id(self):
        """Gets the metadata_persistent_id of this ProductL3Src.  # noqa: E501


        :return: The metadata_persistent_id of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._metadata_persistent_id

    @metadata_persistent_id.setter
    def metadata_persistent_id(self, metadata_persistent_id):
        """Sets the metadata_persistent_id of this ProductL3Src.


        :param metadata_persistent_id: The metadata_persistent_id of this ProductL3Src.  # noqa: E501
        :type metadata_persistent_id: str
        """
        if self.local_vars_configuration.client_side_validation and metadata_persistent_id is None:  # noqa: E501
            raise ValueError("Invalid value for `metadata_persistent_id`, must not be `None`")  # noqa: E501

        self._metadata_persistent_id = metadata_persistent_id

    @property
    def resolution(self):
        """Gets the resolution of this ProductL3Src.  # noqa: E501


        :return: The resolution of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this ProductL3Src.


        :param resolution: The resolution of this ProductL3Src.  # noqa: E501
        :type resolution: str
        """
        if self.local_vars_configuration.client_side_validation and resolution is None:  # noqa: E501
            raise ValueError("Invalid value for `resolution`, must not be `None`")  # noqa: E501

        self._resolution = resolution

    @property
    def product_tif_location(self):
        """Gets the product_tif_location of this ProductL3Src.  # noqa: E501


        :return: The product_tif_location of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._product_tif_location

    @product_tif_location.setter
    def product_tif_location(self, product_tif_location):
        """Sets the product_tif_location of this ProductL3Src.


        :param product_tif_location: The product_tif_location of this ProductL3Src.  # noqa: E501
        :type product_tif_location: str
        """
        if self.local_vars_configuration.client_side_validation and product_tif_location is None:  # noqa: E501
            raise ValueError("Invalid value for `product_tif_location`, must not be `None`")  # noqa: E501

        self._product_tif_location = product_tif_location

    @property
    def product_bag_location(self):
        """Gets the product_bag_location of this ProductL3Src.  # noqa: E501


        :return: The product_bag_location of this ProductL3Src.  # noqa: E501
        :rtype: str
        """
        return self._product_bag_location

    @product_bag_location.setter
    def product_bag_location(self, product_bag_location):
        """Sets the product_bag_location of this ProductL3Src.


        :param product_bag_location: The product_bag_location of this ProductL3Src.  # noqa: E501
        :type product_bag_location: str
        """
        if self.local_vars_configuration.client_side_validation and product_bag_location is None:  # noqa: E501
            raise ValueError("Invalid value for `product_bag_location`, must not be `None`")  # noqa: E501

        self._product_bag_location = product_bag_location

    @property
    def sort_order(self):
        """Gets the sort_order of this ProductL3Src.  # noqa: E501


        :return: The sort_order of this ProductL3Src.  # noqa: E501
        :rtype: float
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this ProductL3Src.


        :param sort_order: The sort_order of this ProductL3Src.  # noqa: E501
        :type sort_order: float
        """
        if self.local_vars_configuration.client_side_validation and sort_order is None:  # noqa: E501
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductL3Src):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductL3Src):
            return True

        return self.to_dict() != other.to_dict()
