/**
 * AusSeabed product catalogue
 * The API description for the Ausseabed product catalogue inventory
 *
 * OpenAPI spec version: 0.1.10
 * Contact: AusSeabed@ga.gov.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Compilation } from './Compilation';
import { ProductL3Src } from './ProductL3Src';
import { HttpFile } from '../http/http';

export class CompilationL3Relation {
    'compilation': Compilation;
    'id': number;
    'productL3Src': ProductL3Src;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compilation",
            "baseName": "compilation",
            "type": "Compilation",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "productL3Src",
            "baseName": "productL3Src",
            "type": "ProductL3Src",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CompilationL3Relation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

