/**
 * AusSeabed product catalogue
 * The API description for the Ausseabed product catalogue inventory
 *
 * OpenAPI spec version: 0.2.2
 * Contact: AusSeabed@ga.gov.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Style } from './Style';
import { HttpFile } from '../http/http';

export class ProductL3Src {
    'id': number;
    'defaultStyle'?: Style;
    'availableStyles'?: Array<Style>;
    'uuid': string;
    'name': string;
    'srs': string;
    'verticalDatum': ProductL3SrcVerticalDatumEnum;
    'metadataPersistentId': string;
    'resolution': string;
    'productTifLocation': string;
    'productBagLocation': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultStyle",
            "baseName": "defaultStyle",
            "type": "Style",
            "format": ""
        },
        {
            "name": "availableStyles",
            "baseName": "availableStyles",
            "type": "Array<Style>",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "srs",
            "baseName": "srs",
            "type": "string",
            "format": ""
        },
        {
            "name": "verticalDatum",
            "baseName": "verticalDatum",
            "type": "ProductL3SrcVerticalDatumEnum",
            "format": ""
        },
        {
            "name": "metadataPersistentId",
            "baseName": "metadataPersistentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "string",
            "format": ""
        },
        {
            "name": "productTifLocation",
            "baseName": "productTifLocation",
            "type": "string",
            "format": ""
        },
        {
            "name": "productBagLocation",
            "baseName": "productBagLocation",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductL3Src.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ProductL3SrcVerticalDatumEnum = "Unknown" | "LAT" | "AHD" | "LMSL" | "WGS84" | "NAD83(HARN)" | "NAD83(CORSxx)" | "NAD83(NSRSxx)" | "NAD83(PACPxx)" | "NAD83(MARPxx)" | "ITRFxx" | "NAVD88" | "NGVD29" | "EGM2008" | "EGM1996" | "EGM1984" | "MLLW" | "MLW" | "MHW" | "MHHW" | "DTL" | "MTL" | "LWD" ;

