/**
 * AusSeabed product catalogue
 * The API description for the Ausseabed product catalogue inventory
 *
 * OpenAPI spec version: 0.2.1
 * Contact: AusSeabed@ga.gov.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SurveyL2RelationDto {
    /**
    * Identifier of the product produced as part of the survey
    */
    'productL2Src': number;
    /**
    * Identifier of the survey that produced the products
    */
    'survey': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productL2Src",
            "baseName": "productL2Src",
            "type": "number",
            "format": ""
        },
        {
            "name": "survey",
            "baseName": "survey",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SurveyL2RelationDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

