/**
 * AusSeabed product catalogue
 * The API description for the Ausseabed product catalogue inventory
 *
 * OpenAPI spec version: 0.2.2
 * Contact: AusSeabed@ga.gov.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductL2Src } from './ProductL2Src';
import { Survey } from './Survey';
import { HttpFile } from '../http/http';

export class SurveyL2Relation {
    'id': number;
    'survey': Survey;
    'productL2Src': ProductL2Src;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "survey",
            "baseName": "survey",
            "type": "Survey",
            "format": ""
        },
        {
            "name": "productL2Src",
            "baseName": "productL2Src",
            "type": "ProductL2Src",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SurveyL2Relation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

