// From https://vdatum.noaa.gov/docs/datums.html
export enum VerticalDatum {
Nad83Harn='NAD83(HARN)', //NAD83(HARN)
Nad83Corsxx='NAD83(CORSxx)', //NAD83(CORSxx)
Nad83Nsrsxx='NAD83(NSRSxx)', //NAD83(NSRSxx)
Nad83Pacpxx='NAD83(PACPxx)', //NAD83(PACPxx)
Nad83Marpxx='NAD83(MARPxx)', //NAD83(MARPxx)
Itrfxx='ITRFxx', //ITRFxx
Wgs84='WGS84', //WGS84
Navd88='NAVD88', //NAVD88
Ngvd29='NGVD29', //NGVD29
Egm2008='EGM2008', //EGM2008
Egm1996='EGM1996', //EGM1996
Egm1984='EGM1984', //EGM1984
Lmsl='LMSL', //LMSL - Local Mean Sea Level **
Mllw='MLLW', //MLLW
Mlw='MLW', //MLW
Mhw='MHW', //MHW
Mhhw='MHHW', //MHHW
Dtl='DTL', //DTL
Mtl='MTL', //MTL
Lwd='LWD', //LWD
Ahd='AHD', // Australian Height Datum
Unknown='Unknown'
};

/**
 * Defines the basic properties of all products
 *
 * @export
 * @interface Product
 */
export interface Product {

  /**
   * The autogenerated id for the product
   *
   * @type {number}
   * @memberof Product
   */
  id: number;

  /**
   * Unique identifier for reference purposes
   *
   * @type {string}
   * @memberof Product
   */
  uuid: string;

  /**
   * Name of product for display purposes - from gazeteer
   *
   * @type {string}
   * @memberof Product
   */
  name: string;

  /**
   * Spatial Reference of product
   *
   * @type {string}
   * @memberof Product
   */
  srs: string;

  /**
   * Persistent Id of final product
   *
   * @type {string}
   * @memberof Product
   */
  metadataPersistentId: string;

}
