import { Survey } from "src/surveys/survey.entity";

/**
 * Defines the basic properties of all products
 *
 * @export
 * @interface Product
 */
export interface Product {

  /**
   * The autogenerated id for the product
   *
   * @type {number}
   * @memberof Product
   */
  id: number;

  /**
   * Unique identifier for reference purposes
   *
   * @type {string}
   * @memberof Product
   */
  uuid: string;

  /**
   * Name of product for display purposes - from gazeteer
   *
   * @type {string}
   * @memberof Product
   */
  name: string;

  /**
   * Spatial Reference of product
   *
   * @type {string}
   * @memberof Product
   */
  srs: string;

  /**
   * Persistent Id of final product
   *
   * @type {string}
   * @memberof Product
   */
  metadataPersistentId: string;

}
