# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import product_catalogue_py_rest_client
from product_catalogue_py_rest_client.models.survey_l2_relation import SurveyL2Relation  # noqa: E501
from product_catalogue_py_rest_client.rest import ApiException

class TestSurveyL2Relation(unittest.TestCase):
    """SurveyL2Relation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SurveyL2Relation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = product_catalogue_py_rest_client.models.survey_l2_relation.SurveyL2Relation()  # noqa: E501
        if include_optional :
            return SurveyL2Relation(
                id = 56, 
                survey = product_catalogue_py_rest_client.models.survey.Survey(
                    id = 56, 
                    uuid = '0', 
                    name = '0', 
                    year = '0', ), 
                product_l2_src = product_catalogue_py_rest_client.models.product_l2_src.ProductL2Src(
                    id = 56, 
                    uuid = '0', 
                    name = '0', 
                    srs = '0', 
                    vertical_datum = 'Unknown', 
                    metadata_persistent_id = '0', 
                    product_gsf_location = '0', 
                    vessel_file_location = '0', 
                    product_posmv_location = '0', )
            )
        else :
            return SurveyL2Relation(
                id = 56,
                survey = product_catalogue_py_rest_client.models.survey.Survey(
                    id = 56, 
                    uuid = '0', 
                    name = '0', 
                    year = '0', ),
                product_l2_src = product_catalogue_py_rest_client.models.product_l2_src.ProductL2Src(
                    id = 56, 
                    uuid = '0', 
                    name = '0', 
                    srs = '0', 
                    vertical_datum = 'Unknown', 
                    metadata_persistent_id = '0', 
                    product_gsf_location = '0', 
                    vessel_file_location = '0', 
                    product_posmv_location = '0', ),
        )

    def testSurveyL2Relation(self):
        """Test SurveyL2Relation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
