# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.1.12
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import product_catalogue_py_rest_client
from product_catalogue_py_rest_client.api.products_l0_dist_api import ProductsL0DistApi  # noqa: E501
from product_catalogue_py_rest_client.rest import ApiException


class TestProductsL0DistApi(unittest.TestCase):
    """ProductsL0DistApi unit test stubs"""

    def setUp(self):
        self.api = product_catalogue_py_rest_client.api.products_l0_dist_api.ProductsL0DistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_l0_dist_controller_create(self):
        """Test case for products_l0_dist_controller_create

        """
        pass

    def test_products_l0_dist_controller_create_instrument(self):
        """Test case for products_l0_dist_controller_create_instrument

        """
        pass

    def test_products_l0_dist_controller_delete(self):
        """Test case for products_l0_dist_controller_delete

        """
        pass

    def test_products_l0_dist_controller_delete_instrument(self):
        """Test case for products_l0_dist_controller_delete_instrument

        """
        pass

    def test_products_l0_dist_controller_find_all(self):
        """Test case for products_l0_dist_controller_find_all

        """
        pass

    def test_products_l0_dist_controller_find_instruments(self):
        """Test case for products_l0_dist_controller_find_instruments

        """
        pass

    def test_products_l0_dist_controller_find_one(self):
        """Test case for products_l0_dist_controller_find_one

        """
        pass

    def test_products_l0_dist_controller_find_one_instrument(self):
        """Test case for products_l0_dist_controller_find_one_instrument

        """
        pass

    def test_products_l0_dist_controller_update(self):
        """Test case for products_l0_dist_controller_update

        """
        pass

    def test_products_l0_dist_controller_update_instrument(self):
        """Test case for products_l0_dist_controller_update_instrument

        """
        pass


if __name__ == '__main__':
    unittest.main()
