# coding: utf-8

"""
    AusSeabed product catalogue

    The API description for the Ausseabed product catalogue inventory  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: AusSeabed@ga.gov.au
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import product_catalogue_py_rest_client
from product_catalogue_py_rest_client.api.product_relations_api import ProductRelationsApi  # noqa: E501
from product_catalogue_py_rest_client.rest import ApiException


class TestProductRelationsApi(unittest.TestCase):
    """ProductRelationsApi unit test stubs"""

    def setUp(self):
        self.api = product_catalogue_py_rest_client.api.product_relations_api.ProductRelationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_product_relations_controller_create_compilation(self):
        """Test case for product_relations_controller_create_compilation

        """
        pass

    def test_product_relations_controller_create_l0_survey(self):
        """Test case for product_relations_controller_create_l0_survey

        """
        pass

    def test_product_relations_controller_create_l2_survey(self):
        """Test case for product_relations_controller_create_l2_survey

        """
        pass

    def test_product_relations_controller_create_l3_survey(self):
        """Test case for product_relations_controller_create_l3_survey

        """
        pass

    def test_product_relations_controller_delete_compilation(self):
        """Test case for product_relations_controller_delete_compilation

        """
        pass

    def test_product_relations_controller_delete_l0_survey(self):
        """Test case for product_relations_controller_delete_l0_survey

        """
        pass

    def test_product_relations_controller_delete_l2_survey(self):
        """Test case for product_relations_controller_delete_l2_survey

        """
        pass

    def test_product_relations_controller_delete_l3_survey(self):
        """Test case for product_relations_controller_delete_l3_survey

        """
        pass

    def test_product_relations_controller_find_all_l0_survey(self):
        """Test case for product_relations_controller_find_all_l0_survey

        """
        pass

    def test_product_relations_controller_find_all_l2_survey(self):
        """Test case for product_relations_controller_find_all_l2_survey

        """
        pass

    def test_product_relations_controller_find_all_l3_compilation(self):
        """Test case for product_relations_controller_find_all_l3_compilation

        """
        pass

    def test_product_relations_controller_find_all_l3_survey(self):
        """Test case for product_relations_controller_find_all_l3_survey

        """
        pass

    def test_product_relations_controller_find_conditional_compilation(self):
        """Test case for product_relations_controller_find_conditional_compilation

        """
        pass

    def test_product_relations_controller_find_conditional_l0_survey(self):
        """Test case for product_relations_controller_find_conditional_l0_survey

        """
        pass

    def test_product_relations_controller_find_conditional_l2_survey(self):
        """Test case for product_relations_controller_find_conditional_l2_survey

        """
        pass

    def test_product_relations_controller_find_conditional_l3_survey(self):
        """Test case for product_relations_controller_find_conditional_l3_survey

        """
        pass

    def test_product_relations_controller_find_one_compilation(self):
        """Test case for product_relations_controller_find_one_compilation

        """
        pass

    def test_product_relations_controller_find_one_l0_survey(self):
        """Test case for product_relations_controller_find_one_l0_survey

        """
        pass

    def test_product_relations_controller_find_one_l2_survey(self):
        """Test case for product_relations_controller_find_one_l2_survey

        """
        pass

    def test_product_relations_controller_find_one_l3_survey(self):
        """Test case for product_relations_controller_find_one_l3_survey

        """
        pass

    def test_product_relations_controller_update_compilation(self):
        """Test case for product_relations_controller_update_compilation

        """
        pass

    def test_product_relations_controller_update_l0_survey(self):
        """Test case for product_relations_controller_update_l0_survey

        """
        pass

    def test_product_relations_controller_update_l2_survey(self):
        """Test case for product_relations_controller_update_l2_survey

        """
        pass

    def test_product_relations_controller_update_l3_survey(self):
        """Test case for product_relations_controller_update_l3_survey

        """
        pass


if __name__ == '__main__':
    unittest.main()
